-- Seed dos bairros (gerado a partir de lib/bairros.ts)
-- Rode DEPOIS do schema.sql. Pode rodar de novo sem duplicar.
insert into servicos (nome, slug) values ('Diarista', 'diarista')
  on conflict (slug) do nothing;

insert into bairros (nome, slug, zona) values
('Sé', 'se', 'Centro'),
('República', 'republica', 'Centro'),
('Higienópolis', 'higienopolis', 'Centro'),
('Consolação', 'consolacao', 'Centro'),
('Bela Vista', 'bela-vista', 'Centro'),
('Bixiga', 'bixiga', 'Centro'),
('Bom Retiro', 'bom-retiro', 'Centro'),
('Brás', 'bras', 'Centro'),
('Cambuci', 'cambuci', 'Centro'),
('Liberdade', 'liberdade', 'Centro'),
('Santa Cecília', 'santa-cecilia', 'Centro'),
('Campos Elíseos', 'campos-eliseos', 'Centro'),
('Pinheiros', 'pinheiros', 'Zona Oeste'),
('Vila Madalena', 'vila-madalena', 'Zona Oeste'),
('Perdizes', 'perdizes', 'Zona Oeste'),
('Lapa', 'lapa', 'Zona Oeste'),
('Barra Funda', 'barra-funda', 'Zona Oeste'),
('Butantã', 'butanta', 'Zona Oeste'),
('Morumbi', 'morumbi', 'Zona Oeste'),
('Alto de Pinheiros', 'alto-de-pinheiros', 'Zona Oeste'),
('Vila Leopoldina', 'vila-leopoldina', 'Zona Oeste'),
('Jaguaré', 'jaguare', 'Zona Oeste'),
('Pompeia', 'pompeia', 'Zona Oeste'),
('Sumaré', 'sumare', 'Zona Oeste'),
('Jardim Paulista', 'jardim-paulista', 'Zona Sul'),
('Jardim América', 'jardim-america', 'Zona Sul'),
('Jardim Europa', 'jardim-europa', 'Zona Sul'),
('Jardim Paulistano', 'jardim-paulistano', 'Zona Sul'),
('Itaim Bibi', 'itaim-bibi', 'Zona Sul'),
('Vila Olímpia', 'vila-olimpia', 'Zona Sul'),
('Vila Mariana', 'vila-mariana', 'Zona Sul'),
('Moema', 'moema', 'Zona Sul'),
('Saúde', 'saude', 'Zona Sul'),
('Ipiranga', 'ipiranga', 'Zona Sul'),
('Jabaquara', 'jabaquara', 'Zona Sul'),
('Campo Belo', 'campo-belo', 'Zona Sul'),
('Brooklin', 'brooklin', 'Zona Sul'),
('Santo Amaro', 'santo-amaro', 'Zona Sul'),
('Vila Andrade', 'vila-andrade', 'Zona Sul'),
('Panamby', 'panamby', 'Zona Sul'),
('Campo Limpo', 'campo-limpo', 'Zona Sul'),
('Capão Redondo', 'capao-redondo', 'Zona Sul'),
('Jardim Ângela', 'jardim-angela', 'Zona Sul'),
('Interlagos', 'interlagos', 'Zona Sul'),
('Cidade Dutra', 'cidade-dutra', 'Zona Sul'),
('Grajaú', 'grajau', 'Zona Sul'),
('Parelheiros', 'parelheiros', 'Zona Sul'),
('Tatuapé', 'tatuape', 'Zona Leste'),
('Anália Franco', 'analia-franco', 'Zona Leste'),
('Mooca', 'mooca', 'Zona Leste'),
('Belém', 'belem', 'Zona Leste'),
('Penha', 'penha', 'Zona Leste'),
('Vila Formosa', 'vila-formosa', 'Zona Leste'),
('Carrão', 'carrao', 'Zona Leste'),
('Itaquera', 'itaquera', 'Zona Leste'),
('Artur Alvim', 'artur-alvim', 'Zona Leste'),
('São Miguel Paulista', 'sao-miguel-paulista', 'Zona Leste'),
('Ermelino Matarazzo', 'ermelino-matarazzo', 'Zona Leste'),
('Guaianases', 'guaianases', 'Zona Leste'),
('Cidade Tiradentes', 'cidade-tiradentes', 'Zona Leste'),
('Sapopemba', 'sapopemba', 'Zona Leste'),
('Vila Prudente', 'vila-prudente', 'Zona Leste'),
('Santana', 'santana', 'Zona Norte'),
('Tucuruvi', 'tucuruvi', 'Zona Norte'),
('Mandaqui', 'mandaqui', 'Zona Norte'),
('Casa Verde', 'casa-verde', 'Zona Norte'),
('Limão', 'limao', 'Zona Norte'),
('Freguesia do Ó', 'freguesia-do-o', 'Zona Norte'),
('Brasilândia', 'brasilandia', 'Zona Norte'),
('Cachoeirinha', 'cachoeirinha', 'Zona Norte'),
('Vila Maria', 'vila-maria', 'Zona Norte'),
('Vila Guilherme', 'vila-guilherme', 'Zona Norte'),
('Jaçanã', 'jacana', 'Zona Norte'),
('Tremembé', 'tremembe', 'Zona Norte'),
('Pirituba', 'pirituba', 'Zona Norte'),
('Jaraguá', 'jaragua', 'Zona Norte'),
('Perus', 'perus', 'Zona Norte')
on conflict (slug) do nothing;
